micronaut:
    application:
        name: veganscan-admin-api

mongodb:
    uri: mongodb://$DATABASE_USER:$DATABASE_PASSWORD@ds139167.mlab.com:39167

vegandb:
    database:
        name: heroku_sfl14q82
